/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matematika_oddiykasirlar;

import java.awt.event.KeyEvent;

/**
 *
 * @author LIVERPOOL
 */
public class LastPage extends javax.swing.JFrame {

    /**
     * Creates new form LastPage
     */
    public LastPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        x = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        y = new javax.swing.JTextField();
        operator = new javax.swing.JComboBox();
        z = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t = new javax.swing.JTextField();
        YECHISH = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        javob = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(350, 50));
        setMinimumSize(new java.awt.Dimension(450, 620));

        jPanel1.setLayout(null);

        x.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        x.setForeground(new java.awt.Color(255, 0, 51));
        x.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                xKeyTyped(evt);
            }
        });
        jPanel1.add(x);
        x.setBounds(80, 30, 40, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matematika_oddiykasirlar/photos/Line.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 70, 50, 10);

        y.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        y.setForeground(new java.awt.Color(255, 0, 0));
        y.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                yKeyTyped(evt);
            }
        });
        jPanel1.add(y);
        y.setBounds(80, 80, 40, 40);

        operator.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-", "*", "/" }));
        operator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorActionPerformed(evt);
            }
        });
        jPanel1.add(operator);
        operator.setBounds(160, 60, 40, 20);

        z.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        z.setForeground(new java.awt.Color(255, 0, 51));
        z.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                zKeyTyped(evt);
            }
        });
        jPanel1.add(z);
        z.setBounds(220, 30, 40, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matematika_oddiykasirlar/photos/Line.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(220, 60, 50, 20);

        t.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        t.setForeground(new java.awt.Color(255, 0, 51));
        t.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tKeyTyped(evt);
            }
        });
        jPanel1.add(t);
        t.setBounds(220, 80, 40, 40);

        YECHISH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matematika_oddiykasirlar/photos/Yeschish.jpg"))); // NOI18N
        YECHISH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                YECHISHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                YECHISHMouseEntered(evt);
            }
        });
        YECHISH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YECHISHActionPerformed(evt);
            }
        });
        jPanel1.add(YECHISH);
        YECHISH.setBounds(270, 70, 100, 40);

        jLabel4.setFont(new java.awt.Font("Myanmar Text", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Javob:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 140, 120, 50);

        javob.setEditable(false);
        javob.setFont(new java.awt.Font("Myanmar Text", 1, 24)); // NOI18N
        javob.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(javob);
        javob.setBounds(210, 130, 210, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matematika_oddiykasirlar/photos/BackgroundForOTHERSPUT.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 450, 620);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void operatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operatorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_operatorActionPerformed

    private void xKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xKeyTyped

        char c = evt.getKeyChar();
      if (!((c >= '0') && (c <= '9') ||
         (c == KeyEvent.VK_BACK_SPACE) ||
         (c == KeyEvent.VK_DELETE))) {
        getToolkit().beep();
        evt.consume();
      }
    }//GEN-LAST:event_xKeyTyped

    private void yKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yKeyTyped
   char c = evt.getKeyChar();
      if (!((c >= '0') && (c <= '9') ||
         (c == KeyEvent.VK_BACK_SPACE) ||
         (c == KeyEvent.VK_DELETE))) {
        getToolkit().beep();
        evt.consume();
      }        // TODO add your handling code here:
    }//GEN-LAST:event_yKeyTyped

    private void zKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zKeyTyped
   char c = evt.getKeyChar();
      if (!((c >= '0') && (c <= '9') ||
         (c == KeyEvent.VK_BACK_SPACE) ||
         (c == KeyEvent.VK_DELETE))) {
        getToolkit().beep();
        evt.consume();
      }        // TODO add your handling code here:
    }//GEN-LAST:event_zKeyTyped

    private void tKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tKeyTyped
   char c = evt.getKeyChar();
      if (!((c >= '0') && (c <= '9') ||
         (c == KeyEvent.VK_BACK_SPACE) ||
         (c == KeyEvent.VK_DELETE))) {
        getToolkit().beep();
        evt.consume();
      }        // TODO add your handling code here:
    }//GEN-LAST:event_tKeyTyped

    private void YECHISHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YECHISHActionPerformed
        

      int xNum=Integer.parseInt(x.getText());
      int yNum=Integer.parseInt(y.getText());
      int zNum=Integer.parseInt(z.getText());
      int tNum=Integer.parseInt(t.getText());
      Fraction fractionOne= new Fraction(xNum,yNum);
      Fraction fractionTwo= new Fraction(zNum,tNum);
      String operand=operator.getSelectedItem().toString();
         
         if(operand == "+")
         {
             javob.setText(fractionOne.addFraction(fractionTwo));
         }
         if(operand == "-")
         {
             javob.setText(fractionOne.subtractFraction(fractionTwo));
         }
         if(operand == "/")
         {
             javob.setText(fractionOne.divideByFraction(fractionTwo));
             
         }
          if(operand == "*")
          {
              javob.setText(fractionOne.multiplyByFraction(fractionTwo));
              
          }      
      
        
    }//GEN-LAST:event_YECHISHActionPerformed

    private void YECHISHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YECHISHMouseClicked

    }//GEN-LAST:event_YECHISHMouseClicked

    private void YECHISHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YECHISHMouseEntered
  if(x.getText().equals("") || y.getText().equals("") || z.getText().equals("") || t.getText().equals("")) 
{
    YECHISH.setEnabled(false);
}else
{
     YECHISH.setEnabled(true);
    
}
    }//GEN-LAST:event_YECHISHMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LastPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LastPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LastPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LastPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LastPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton YECHISH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField javob;
    private javax.swing.JComboBox operator;
    private javax.swing.JTextField t;
    private javax.swing.JTextField x;
    private javax.swing.JTextField y;
    private javax.swing.JTextField z;
    // End of variables declaration//GEN-END:variables
}
